---
- name: Install dependencies for nginx build
  apt: pkg={{ item }} state=present
  with_items:
    - libreadline-dev
    - libncurses5-dev
    - libpcre3-dev
    - libssl-dev
    - perl
    - make
    - git
    - curl
    - checkinstall
