---
- name: Ensure we have apt-transport-https installed
  apt: pkg=apt-transport-https state=present update_cache=yes
  sudo: yes

- name: Install the key
  apt_key: id=36A1D7869245C8950F966E92D8576A8BA88D21E9 keyserver=hkp://keyserver.ubuntu.com:80 state=present
  sudo: yes


- name: Add the repository
  apt_repository: repo='deb https://get.docker.io/ubuntu docker main' state=present
  sudo: yes

- name: Install docker
  apt: pkg=lxc-docker state=present update_cache=yes
  sudo: yes

- name: Ensure pip is installed
  apt: pkg=python-pip state=present
  sudo: yes

- name: Install the docker-py client via pip
  pip: name=docker-py state=present
  sudo: yes
